### ISSUE TITLE
Error at method call cvLoadHaarClassifierCascade

### ISSUE THREAD

**Issue by vishalkadavale** [bytedeco/javacv-examples#11]
Hello,
I am working on windows 7 platform with jdk1.8, I am getting following error. I tried a lot but unable to find the reason why getting this error, error snap is as follows.

Exception in thread "main" java.lang.NoSuchMethodError: putMemberOffset
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
at java.lang.Runtime.load0(Runtime.java:795)
at java.lang.System.load(System.java:1062)
at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:637) at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:637)
at org.bytedeco.javacpp.Loader.load(Loader.java:492)
at org.bytedeco.javacpp.Loader.load(Loader.java:409)
at org.bytedeco.javacpp.opencv_core.(opencv_core.java:10)
at detection.Example1.loadFaceCascade(Example1.java:36)
at detection.Example1.main(Example1.java:140)
Error getting static method ID of org/bytedeco/javacpp/Loader/putMemberOffset

Please help me!
I added following libraries in project.
opencv-3.0.0-1.0.jar
opencv-3.0.0-1.0-windows-x86.jar
opencv-3.0.0-1.0-windows-x86_64.jar
javacpp-1.0.jar
javacv-1.0.jar

Also tried different versions of these libraries but not worked out.

**Comment by saudet** [comment]
Try again with version 1.2.

**Comment by vishalkadavale** [comment]
Issue solved! I used flandmark 1.07-1.0 with opencv3.0.0 .
Thank You very much!
